<?php

use Illuminate\Database\Seeder;

class DetallesUpzUprSeguimientoProyectoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbl_parametros_detalles')->insert([
            [
                'vc_parametro_detalle' => '1. PASEO DE LOS LIBERTADORES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '9. VERBENAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '10. LA URIBE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '11. SAN CRISTOBAL NORTE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '12. TOBERIN',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '13. LOS CEDROS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '14. USAQUEN',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '15. COUNTRY CLUB',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '16. SANTA BARBARA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 200,
            ],
            [
                'vc_parametro_detalle' => '88. EL REFUGIO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 201,
            ],
            [
                'vc_parametro_detalle' => '89. SAN ISIDRO PATIOS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 201,
            ],
            [
                'vc_parametro_detalle' => '90. PARDO RUBIO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 201,
            ],
            [
                'vc_parametro_detalle' => '97. CHICO LAGO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 201,
            ],
            [
                'vc_parametro_detalle' => '99. CHAPINERO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 201,
            ],
            [
                'vc_parametro_detalle' => '91. SAGRADO CORAZON',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 202,
            ],
            [
                'vc_parametro_detalle' => '92. LA MACARENA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 202,
            ],
            [
                'vc_parametro_detalle' => '93. LAS NIEVES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 202,
            ],
            [
                'vc_parametro_detalle' => '95. LAS CRUCES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 202,
            ],
            [
                'vc_parametro_detalle' => '96. LOURDES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 202,
            ],
            [
                'vc_parametro_detalle' => '32. SAN BLAS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 203,
            ],
            [
                'vc_parametro_detalle' => '33. SOSIEGO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 203,
            ],
            [
                'vc_parametro_detalle' => '34. 20 DE JULIO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 203,
            ],
            [
                'vc_parametro_detalle' => '50. LA GLORIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 203,
            ],
            [
                'vc_parametro_detalle' => '51. LOS LIBERTADORES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 203,
            ],
            [
                'vc_parametro_detalle' => '52. LA FLORA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '56. DANUBIO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '57. GRAN YOMASA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '58. COMUNEROS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '59. ALFONSO LOPEZ',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '60. PARQUE ENTRENUBES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '61. CIUDAD DE USME',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '200. UPR 3 USME',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 204,
            ],
            [
                'vc_parametro_detalle' => '42. VENECIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 205,
            ],
            [
                'vc_parametro_detalle' => '62. TUNJUELITO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 205,
            ],
            [
                'vc_parametro_detalle' => '49. APOGEO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 206,
            ],
            [
                'vc_parametro_detalle' => '84. BOSA OCCIDENTAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 206,
            ],
            [
                'vc_parametro_detalle' => '85. BOSA CENTRAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 206,
            ],
            [
                'vc_parametro_detalle' => '86. EL PORVENIR',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 206,
            ],
            [
                'vc_parametro_detalle' => '87. TINTAL SUR E',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 206,
            ],
            [
                'vc_parametro_detalle' => '44. AMERICAS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '45. CARVAJAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '46. CASTILLA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '47. KENNEDY CENTRAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '48. TIMIZA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '78. TINTAL NORTE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '79. CALANDAIMA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '80. CORABASTOS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '81. GRAN BRITALIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '82. PATIO BONITO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],[
                'vc_parametro_detalle' => '83. LAS MARGARITAS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '113. BAVARIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 207,
            ],
            [
                'vc_parametro_detalle' => '75. FONTIBÓN CENTRO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '76. FONTIBÓN SAN PABLO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '77. ZONA FRANCA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '110. CIUDAD SALITRE OCCIDENTE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '112. GRANJAS DE TECHO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '114. MODELIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '115. CAPELLANÍA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '117. AEROPUERTO EL DORADO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 208,
            ],
            [
                'vc_parametro_detalle' => '26. LAS FERIAS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '29. MINUTO DE DIOS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '30. BOYACA REAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '31. SANTA CECILIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '72. BOLIVIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '73. GARCES NAVAS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '74. ENGATIVA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '105. JARDIN BOTANICO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '116. ALAMOS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 209,
            ],
            [
                'vc_parametro_detalle' => '2. LA ACADEMIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '3. GUAYMARAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '17. SAN JOSÉ DE BAVARIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '18. BRITALIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '19. EL PRADO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '20. LA ALHAMBRA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '23. CASA BLANCA SUBA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '24. NIZA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '25. LA FLORESTA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '27. SUBA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '28. EL RINCÓN',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '71. TIBABUYES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '0. UPR ZONA NORTE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 210,
            ],
            [
                'vc_parametro_detalle' => '21. LOS ANDES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 211,
            ],
            [
                'vc_parametro_detalle' => '22. DOCE DE OCTUBRE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 211,
            ],
            [
                'vc_parametro_detalle' => '98. LOS ALCAZARES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 211,
            ],
            [
                'vc_parametro_detalle' => '103. PARQUE SALITRE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 211,
            ],
            [
                'vc_parametro_detalle' => '100. GALERIAS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 212,
            ],
            [
                'vc_parametro_detalle' => '101. TEUSAQUILLO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 212,
            ],
            [
                'vc_parametro_detalle' => '104. PARQUE SIMON BOLIVAR-CAN',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 212,
            ],
            [
                'vc_parametro_detalle' => '106. LA ESMERALDA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 212,
            ],
            [
                'vc_parametro_detalle' => '107. QUINTA PAREDES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 212,
            ],
            [
                'vc_parametro_detalle' => '109. CIUDAD SALITRE ORIENTAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 212,
            ],
            [
                'vc_parametro_detalle' => '37. SANTA ISABEL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 213,
            ],
            [
                'vc_parametro_detalle' => '102. LA SABANA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 213,
            ],
            [
                'vc_parametro_detalle' => '35. CIUDAD JARDIN',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 214,
            ],
            [
                'vc_parametro_detalle' => '38. RESTREPO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 214,
            ],
            [
                'vc_parametro_detalle' => '40. CIUDAD MONTES',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 215,
            ],
            [
                'vc_parametro_detalle' => '41. MUZU',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 215,
            ],
            [
                'vc_parametro_detalle' => '43. SAN RAFAEL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 215,
            ],
            [
                'vc_parametro_detalle' => '108. ZONA INDUSTRIAL',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 215,
            ],
            [
                'vc_parametro_detalle' => '111. PUENTE ARANDA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 215,
            ],
            [
                'vc_parametro_detalle' => '94. CANDELARIA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 216,
            ],
            [
                'vc_parametro_detalle' => '36. SAN JOSE',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 217,
            ],
            [
                'vc_parametro_detalle' => '39. QUIROGA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 217,
            ],
            [
                'vc_parametro_detalle' => '53. MARCO FIDEL SUAREZ',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 217,
            ],
            [
                'vc_parametro_detalle' => '54. MARRUECOS',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 217,
            ],
            [
                'vc_parametro_detalle' => '55. DIANA TURBAY',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 217,
            ],
            [
                'vc_parametro_detalle' => '63. EL MOCHUELO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '64. MONTEBLANCO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '65. ARBORIZADORA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '66. SAN FRANCISCO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '67. LUCERO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '68. EL TESORO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '69. ISMAEL PERDOMO',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '70. JERUSALÉN',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
            [
                'vc_parametro_detalle' => '919. CORREGIMIENTO MOCHUELO, QUIBA Y  PASQUILLA',
                'i_fk_id_parametro' => 31,
                'i_estado' => 1,
                'i_fk_id_padre' => 218,
            ],
        ]);
    }
}
