<?php

use Illuminate\Database\Seeder;

class DetalleTipoBienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbl_parametros_detalles')->insert([
            [
				'vc_parametro_detalle' => 'Accesorios y repuestos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77 ,
			],
			[
				'vc_parametro_detalle' => 'Acepillado, incluye fabricación de listón y molduras en blanco',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82 ,
			],
			[
				'vc_parametro_detalle' => 'Agua potable',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 2.65 ,
			],
			[
				'vc_parametro_detalle' => 'Ajonjolí',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91 ,
			],
			[
				'vc_parametro_detalle' => 'Algodón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90 ,
			],
			[
				'vc_parametro_detalle' => 'Arenas industriales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.89 ,
			],
			[
				'vc_parametro_detalle' => 'Arenas y gravillas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91 ,
			],
			[
				'vc_parametro_detalle' => 'Arroz',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90 ,
			],
			[
				'vc_parametro_detalle' => 'Aserrado de madera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84 ,
			],
			[
				'vc_parametro_detalle' => 'Café',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.94 ,
			],
			[
				'vc_parametro_detalle' => 'Caña de azúcar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.88 ,
			],
			[
				'vc_parametro_detalle' => 'Carbón mineral',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.86 ,
			],
			[
				'vc_parametro_detalle' => 'Cebolla',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.92 ,
			],
			[
				'vc_parametro_detalle' => 'Comercio',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.75 ,
			],
			[
				'vc_parametro_detalle' => 'Comunicaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de artículos de camisería',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de cortinas y artículos de ornamentación con Materiales textiles, incluye los de material plástico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de prendas de vestir de cuero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de ropa exterior para mujer y niña',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de ropa interior para mujer y niña',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de ropa para bebe',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de ropa para cama',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de ropa para trabajo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Confección de vestidos de baño',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Conservación y tratamiento de la madera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82 ,
			],
			[
				'vc_parametro_detalle' => 'Construcción industrial',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Construcción y reconstrucción de embarcaciones mayores',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Construcción y reconstrucción de embarcaciones menores',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76 ,
			],
			[
				'vc_parametro_detalle' => 'Curtido y acabado de cuero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76 ,
			],
			[
				'vc_parametro_detalle' => 'Deshidratación de frutas, legumbres y otros vegetales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.88 ,
			],
			[
				'vc_parametro_detalle' => 'Desmote y preparación del algodón para el hilado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85 ,
			],
			[
				'vc_parametro_detalle' => 'Destilación de alcohol etílico, para todos los usos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84 ,
			],
			[
				'vc_parametro_detalle' => 'Divisas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.18 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de aceites esenciales, resinas y mezclas, excepto los derivados de la destilación de maderas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de alimentos para aves, incluso los complementarios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de alimentos para ganado, incluso los complementarios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.86 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de alimentos para perros, gatos y otros animales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de combustibles derivados del petróleo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de malta',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Elaboración de mezclas de abonos orgánicos y naturales, estiércol, residuos vegetales y escorias',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77 ,
			],
			[
				'vc_parametro_detalle' => 'Encuadernación',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78 ,
			],
			[
				'vc_parametro_detalle' => 'Energía eléctrica industrial',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90 ,
			],
			[
				'vc_parametro_detalle' => 'Energía eléctrica sector agropecuario',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.40 ,
			],
			[
				'vc_parametro_detalle' => 'Energía eléctrica servicios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Envase de carnes en conserva en recipientes herméticos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81 ,
			],
			[
				'vc_parametro_detalle' => 'Equipos de oficina',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Equipos de transporte',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Excedente bruto de explotación (p.m.), industria manufacturera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87 ,
			],
			[
				'vc_parametro_detalle' => 'Excedente bruto de explotación (p.m.), sector agropecuario',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91 ,
			],
			[
				'vc_parametro_detalle' => 'Excedente bruto de explotación (p.m.), sector servicios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80 ,
			],
			[
				'vc_parametro_detalle' => 'Excedente bruto de explotación (p.m.), sector transporte',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80 ,
			],
			[
				'vc_parametro_detalle' => 'Extracción y refinación de manteca de cerdo y otras grasas Animales comestibles y subproductos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación  de artículos fundidos de aluminio y sus aleaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación  de productos de alambre',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de  calzado no incluido antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de abonos nitrogenados, fosfáticos y potásicos puros, mixtos, compuestos y complejos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de accesorios eléctricos para alumbrado deuso general',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de acero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de agujas, alfileres, broches, cremalleras y artículos metálicos de mercería n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de almidones, féculas y productos derivados, incluye gluten y harina de gluten',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos de soldadura eléctricos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80 ,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos eléctricos de limpieza y de plantar eléctrico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>	 0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos eléctricos y utensilios de cocina para la preparación de alimentos, tales como licuadoras, batidoras etc.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos sanitarios y accesorios para fontanería elaborados en cerámica',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos telefónicos y telegráficos para líneas eléctricas de comunicaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos transmisores y receptores de radiodifusión y televisión',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.86,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos transmisores y receptores de radiotelefonía y radio – telegrafía',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos y elementos para radio, televisión y comunicaciones , no incluidos antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos y equipos similares no incluidos antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de aparatos y máquinas para la avicultura',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artefactos sanitarios y accesorios metálicos de fontanería',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de acería laminados en caliente',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de acería laminados en frío',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de caucho para usos higiénicos, farmacéuticos y de laboratorio',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de caucho para usos industriales y mecánicos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de cordelería – mallas, hamacas, Redes y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de ferretería y cerrajería n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de fibra y lana de vidrio',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de fibras artificiales y/o sintéticas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de hierro y acero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de lona',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de pirotecnia',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de plástico para el hogar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de tejido de punto n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos de vidrio para la construcción y usos técnico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.89,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos fundidos y forjados de cobre y sus aleaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.76,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos laminados, estirados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos laminados, estirados y extruidos de Aluminio y su aleación',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de artículos refractarios para la construcción y la industria',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.87,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de asfalto y sus mezclas para pavimentación, techado y construcción',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de ataúdes, urnas funerarias y artículos de madera no incluidos antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de automóviles',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de autopartes no incluidos antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de azulejos y baldosas de loza o porcelana',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.84,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de barrigas y tambores metálicos de gran capacidad para embalaje: almacenamiento y transporte',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de básculas y balanzas, excepto instrumentos de laboratorio',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de bebidas no alcohólicas gasificadas o sin gasificar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			], 
			[
				'vc_parametro_detalle' => 'Fabricación de cajas de cartón acanalado y envases de fibra',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cajas de cartón plegables y armadas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cajas de madera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cajas fuertes y compartimientos blindados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cal y carbonatos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calderas y motores marinos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calzado de caucho y sus partes, incluye el calzado de caucho y textiles',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calzado de cuero para hombres',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.76,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calzado de cuero para niño',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.76,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calzado de tela, sandalias, pantuflas y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calzado deportivo de cuero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de calzado para mujer',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.76,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de carrocerías y chasises para vehículos automotores',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de carros, sillones de ruedas y vehículos similares para inválido',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de carteras y artículos de marroquinería (niqueleros, billeteras)',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cartón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de celulosa regenerada, sus derivados químicos y fibra vulcanizada',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cemento',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de chocolate y preparados de cacao',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.86,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cigarrillos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.84,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cigarros',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de cojinetes de bolas y rodillos, pistones, válvulas y piezas de maquinaria  para usos generales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de colas, adhesivos, cementos sintéticos y aprestos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de compresores y bombas de agua y otros líquidos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de computadores, minicomputadores, máquinas electrónicas sus accesorios y sus partes ',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.86,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de dispositivos recorridos por una corriente, tales como enchufes interruptores, conectores de cables, etc.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de elementos estructurales metálicos, con los instalados que no pueden declararse por separado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de elementos metálicos para arquitectura y ornamentación',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de elementos para billares, boleras y juegos similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de elementos para taller de calderas, aun los instalados que no pueden declarse por separado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de envases y artículos de vidrio para uso industrial',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.85,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de envases y recipientes metálicos diversos, excepto aquellos de gran capacidad destinados a embalaje, almacenamiento y transporte',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de envases, cajas y vasijas de material plástico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de equipo eléctrico auxiliar para motores de combustión interna',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de equipo para atomización de líquidos o polvos, incluye los atomizadores domésticos ',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de equipos de aire acondicionado, excepto conductos y otros elementos análogos de chapa metálica ',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de estructuras obras y accesorios en madera para la construcción',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de explosivos, municiones y detonantes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de fibra y lana de vidrio',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de fibras celulósicas y otras artificiales, excepto el vidrio, en forma de monofilamentos, mechones o haces adecuados para trabajarlos después en máquinas textiles',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de filamento eléctrico, lámparas de descarga y de arco voltaico y bombillas de flash',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de formas básicas de caucho, planchas, laminas, tubos y productos análogos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de formas básicas de plástico, laminas, películas varilla, tubos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de fósforos y cerillas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de frazadas, mantas, ruanas y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de gases industriales, excepto el cloro y otros halógenos, gas natural y otros hidrocarburos crudos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de géneros de algodón y encajes en tejido de punto',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de géneros y encajes de fibras artificiales y/o Sintéticas en tejido de punto',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de goma de mascar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de grupos electrógenos (plantas generadoras de electricidad)',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de guantes, corbatas, pañuelos, pañoletas y otras prendas similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de guatas y artículos de guata',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.75,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de hamacas con tejidos planos de algodón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.84,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de helados, sorbetes y postres a base de leche',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de herramientas manuales para uso agrícola Forestal y jardinería',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de herramientas para mecánica carpintería y  construcción',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de hilos y cables aislados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de hules y telas impregnadas e impermeabilizadas, Incluye el cuero artificial',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de impermeables',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de instrumentos de cuerda y arco e instrumentos de cuerda punteados, excepto los electrónicos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de instrumentos para la regulación y control de las operaciones industriales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de instrumentos, aparatos y accesorios de medicina, cirugía, odontología y veterinaria, excepto los instrumentos de óptica y los aparatos de rayos X y electroterapia',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de joyas de oro, plata y platino',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de lacas en general',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de ladrillo, baldosas y  teja de arcilla',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de levadoras y polvos para hornear',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de llantas de caucho',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maderas aglomeradas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maderas contrachapadas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de mantequilla y crema de leche',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.85,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria especial para trabajar madera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.74,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria para aserraderos y de aplicaciones generales para trabajar madera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria para elaborar alimentos y bebidas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria para fabricar pulpa, papel y cartón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria para ser remolcada',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria y equipo para elaborar caucho',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.76,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria y equipo para servicios n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de maquinaria y equipos especiales para la construcción',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de máquinas de escribir',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.73,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de margarinas y grasas compuestas para cocinar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de materias colorantes orgánicas, extractos tintóreos y materias curtientes orgánicas, sintéticas, etc.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de materias sintéticas por polimerización y copolimerización, incluye caucho y látex sintéticos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de melazas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de menajes de cocina, piezas y otros productos catampados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de monedas metálicas emitidas por el estado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de motocicletas, motonetas y velocípedos con motor  auxiliar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.74,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de motores de combustión interna, excepto para automotores ',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de motores y cajas de velocidad para vehículos automotores, se excluyen los grupos electrógenos y los motores eléctricos de tracción',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de motores y generadores energía',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de muebles de mimbre, caña y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de muebles para aparatos eléctricos, maquinas de coser y otros',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de muebles y accesorios metálicos para comercio y servicios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de muebles y accesorios metálicos para oficina',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de muebles y productos de plástico no incluidos antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de muñecas y accesorios para muñecas, marionetas, títeres y animales de juguete',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otras resinas y materias plásticas artificiales, incluso las obtenidas de materias vegetales y animales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otras sustancias químicas y productos químicos Derivados del petróleo, carbón, caucho y plástico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otros aparatos, accesorios y artículos electrónicos n.e.p., tales como timbres, alarmas, incubadoras y criadoras y otros n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otros artículos de metal',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otros preparados químicos n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=>0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otros productos minerales no metálicos excepto los derivados de petróleo y carbón ',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de otros productos químicos inorgánicos, excepto los radioactivos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de papel',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de papel y cartón n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de papeles especiales, satinados, encerados, Laminados y otros papeles acabados fuera de máquina',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de paraguas, sombrillas, bastones y artículos similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de partes y accesorios n.e.p. para motocicletas, bicicletas y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de partes y piezas para equipo ferroviario',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de película tubular y tripas sintéticas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.88,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de piezas de hierro o acero forjados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.75,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de piezas y accesorios para máquinas – herramientas y herramientas de medición para maquinistas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de pinturas y barnices para uso general e industrial',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de plantas y de maquinaria y equipos especiales para elaborar productos químicos y para refinar petróleo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de plástico espumado y artículos de plástico Espumado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de prendas de vestir especiales, togas Académicas, hábitos religiosos y otros disfraces',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos de asbesto - cemento',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos de asbesto, hilados, tejidos, fieltros etc',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos de chapa metálica',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos de corcho',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos de hormigón, incluye prefabricados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos químicos industriales inorgánicos, excepto los gases que no sean del cloro y otros halógenos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos químicos orgánicos no incluidos antes, excepto los gases industriales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos químicos orgánicos, compuestos cíclicos y acíclicos excepto los gases industriales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos químicos para fotografía de películas, placas sensibilizadas y papeles fotográficos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de productos vegetales, excepto antibióticos, a base de materias naturales y producidos sintéticamente',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.86,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de puertas y ventanas metálicas y sus partes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de puertas, ventanas y sus partes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de pulpa de madera, bagazo, trapos y fibras n.e.p',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de repuestos y accesorios de plástico para uso  industrial, incluye muebles para aparatos electrónicos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de ropa de algodón en tejido de punto',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de ropa de lana en tejido de punto',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de sacos y bolsas de papel',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de sistemas y conjuntos de elementos principales Para reproducción, transmisión y recepción de sonido e imagen; se excluyen los elementos para líneas de comunicación',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de sombreros y partes para sombreros',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tapetes y alfombras hechos principalmente de algodón ',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tejidos planos de algodón esponjosos o afelpados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tejidos planos de algodón, telas, driles. Lonas y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tejidos planos de fibras artificiales y sintéticas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tejidos planos de lana, paños y telas de lana',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tintas para imprenta, escribir, dibujar y demás',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tornillería en general',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de transformadores, convertidores y rectificadores excepto los especialmente concebidos para radio, TV comunicaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de tubos y accesorios de arcilla',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de vajillas y utensilios análogos de vidrio',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de válvulas y accesorios metálicos para tubería Excepto válvulas con dispositivos reguladores y artículos de fontanería de latón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de vehículos manuales, excepto los sillones de ruedas para inválidos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de vehículos pesados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de velocípedos – bicicletas, triciclos y vehículos análogos motonetas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de vidrio de seguridad y vidrio templado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de vidrio en formas primarias',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.92,
			],
			[
				'vc_parametro_detalle' => 'Fabricación de yeso y productos de yeso',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Fabricación y mezcla de insecticidas, plaguicidas y reguladores fisiológicos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Fabricación y reconstrucción de motores para aeronaves',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.88,
			],
			[
				'vc_parametro_detalle' => 'Fabricación y refinación de azúcar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'FC consumo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'FC inversión agropecuaria',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91,
			],
			[
				'vc_parametro_detalle' => 'FC inversión industrial',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'FC inversión servicios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'FC inversión transporte',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Ferroaleaciones  y sus productos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Galletería',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Ganado de res',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
			[
				'vc_parametro_detalle' => 'Ganancias extraordinarias normativas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.0,
			],
			[
				'vc_parametro_detalle' => 'Gas natural',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'Gasoducto',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Grabado, fotograbado, electrotipía, estereotipía y fotomecánica',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Guarnecido y punteado de calzado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.75,
			],
			[
				'vc_parametro_detalle' => 'Hidrogenación de aceites y grasas vegetales y animales Purificados o no',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Hilado de algodón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Hilado y tejido de fibras duras vegetales, incluye sacos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Hilados de fibras animales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Impuestos indirectos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.0,
			],
			[
				'vc_parametro_detalle' => 'Industrias manufactureras n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Insumos varios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Lavado y preparación de tripas y aprovechamiento de otros subproductos de matadero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.72,
			],
			[
				'vc_parametro_detalle' => 'Leche fresca',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91,
			],
			[
				'vc_parametro_detalle' => 'Maíz',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra administrativa',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.49,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra administrativa, sectores de elevadas prestaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.41,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra extranjera',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.00,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra no calificada',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.60,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra no calificada rural',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.00,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra no calificada, sectores de elevadas prestaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.46,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra profesional',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.00,
			],
			[
				'vc_parametro_detalle' => 'Mano de obra profesional, sectores de elevadas prestaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'Maquinarias agrícolas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Maquinarias y equipos industriales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Matanza de aves de corral y de animales de caza menor con o sin frigorífico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Matanza de ganado mayor con o sin frigorífico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Molienda y tostado de café, incluso café soluble y extractos de café',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Mondado, prensado y elaboración de harinas de cereales y leguminosas n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Obra Física',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Obreros calificados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.60,
			],
			[
				'vc_parametro_detalle' => 'Obreros calificados, sectores de elevadas prestaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.46,
			],
			[
				'vc_parametro_detalle' => 'Otras fabricaciones de productos metálicos, maquinaria y equipo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Otras industrias de la madera y sus productos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Otras industrias manufactureras',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Otras industrias metálicas básicas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Otros',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Otros agrícolas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91,
			],
			[
				'vc_parametro_detalle' => 'Otros minerales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
			[
				'vc_parametro_detalle' => 'Otros productos alimenticios, bebidas y tabaco',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76,
			],
			[
				'vc_parametro_detalle' => 'Otros productos de papel, imprentas y editoriales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Otros textiles, prendas de vestir e industrias de cuero',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.76,
			],
			[
				'vc_parametro_detalle' => 'Papa',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.91,
			],
			[
				'vc_parametro_detalle' => 'Pasteurización, homogeneización, vitaminación y embotellado De leche líquida',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.89,
			],
			[
				'vc_parametro_detalle' => 'Piedra caliza',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'Porcinos, ovinos y otros pecuarios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.86,
			],
			[
				'vc_parametro_detalle' => 'Preparación de  hormigón',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Preparación de carnes frías y otras carnes no envasadas, jamones, tocinetas, salchichas, embutidos, etc.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Preparación de harinas mezcladas de cereales y leguminosas y productos similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Preparación de la hoja de tabaco',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Preparación de mezclas para alimentación infantil',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Preparación de otras bebidas alcohólicas similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Preparación de pescado y otros animales marinos y de agua Dulce comestibles, frescos, refrigerados o congelados rápidamente',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.88,
			],
			[
				'vc_parametro_detalle' => 'Preparación de productos para tratar metales, auxiliares para soldadura, recubrimientos para electrodos y similares',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Preparación e hilado de fibras artificiales y/o sintéticas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Producción de aceites y grasas lubricantes que no se elaboran en las refinerías de petróleo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.89,
			],
			[
				'vc_parametro_detalle' => 'Producción de aceites y grasas vegetales sin refinar y Residuos de la extracción',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'Producción de casas prefabricadas y sus partes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Producción de harina de maíz y pilado de maíz',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'Producción de harina de trigo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Producción de leches y productos lácteos conservados',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Producción de pigmentos y materias colorantes n.e.p. para la Fabricación de colores, barnices, lacas, esmaltes, etc.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Producción de sustancias y aditamentos alimenticios para Animales, incluso harinas de ostras, hueso y pescado',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Producción de vitaminas y provitaminas de materias naturales y sintéticas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Producción y fabricación de otros productos minerales no metálicos, no incluidos antes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Productos avícolas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.86,
			],
			[
				'vc_parametro_detalle' => 'Productos de extractos y jarabes de frutas, cereales y otros vegetales',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Productos medicinales y farmacéuticos n.e.p.',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Reconstrucción de motores y otras partes de vehículos excepto el equipo eléctrico',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Recuperación y elaboración de otros metales no ferrosos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Recuperación y fundición de cobre, incluye coproalineaciones',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.83,
			],
			[
				'vc_parametro_detalle' => 'Recuperación y fundición de plomo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.84,
			],
			[
				'vc_parametro_detalle' => 'Reducción de mineral de hierro',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.73,
			],
			[
				'vc_parametro_detalle' => 'Refinación de aceites y grasas vegetales, no incluye la hidrogenación',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.85,
			],
			[
				'vc_parametro_detalle' => 'Refinación, laminación y fundición de oro',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Reparación de embarcaciones mayores',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Reparación de embarcaciones menores',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.81,
			],
			[
				'vc_parametro_detalle' => 'Reparación de locomotoras y equipos ferroviarios',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.72,
			],
			[
				'vc_parametro_detalle' => 'Reparación y mantenimiento de aeronaves',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.92,
			],
			[
				'vc_parametro_detalle' => 'Reproducción de discos de gramófono, cintas magnetofónicas y vídeo – cintas',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Sal marina sin purificar',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.86,
			],
			[
				'vc_parametro_detalle' => 'Servicios agropecuarios – fumigación aérea',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.78,
			],
			[
				'vc_parametro_detalle' => 'Servicios agropecuarios – maquinaria',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Servicios agropecuarios – riego',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Servicios agropecuarios – yunta',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.87,
			],
			[
				'vc_parametro_detalle' => 'Servicios industriales de terceros',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.77,
			],
			[
				'vc_parametro_detalle' => 'Servicios y seguros',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.71,
			],
			[
				'vc_parametro_detalle' => 'Sorgo',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.89,
			],
			[
				'vc_parametro_detalle' => 'Soya',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
			[
				'vc_parametro_detalle' => 'Subproductos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.00,
			], 
			[
				'vc_parametro_detalle' => 'Terrenos',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 1.00,
			], 
			[
				'vc_parametro_detalle' => 'Tipografías y litografías',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Tomate',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.92,
			],
			[
				'vc_parametro_detalle' => 'Transporte',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.75,
			],
			[
				'vc_parametro_detalle' => 'Transporte de larga distancia con dos ejes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.79,
			],
			[
				'vc_parametro_detalle' => 'Transporte de larga distancia con tres ejes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.71,
			],
			[
				'vc_parametro_detalle' => 'Transporte de larga distancia con tres ejes y con remolque de dos ejes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.71,
			],
			[
				'vc_parametro_detalle' => 'Transporte de media distancia con dos ejes',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.75,
			],
			[
				'vc_parametro_detalle' => 'Trilla – pilado – de arroz',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.88,
			],
			[
				'vc_parametro_detalle' => 'Trilla de café',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
			[
				'vc_parametro_detalle' => 'Trituración aserrado y talla de mármol',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.82,
			],
			[
				'vc_parametro_detalle' => 'Trituración aserrado y talla de piedra',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.80,
			],
			[
				'vc_parametro_detalle' => 'Yuca',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
			[
				'vc_parametro_detalle' => 'Zanahoria',
				'i_fk_id_parametro'=>47,
				'i_estado'=>1,
				'd_rpc'=> 0.90,
			],
        ]);
    }
}
