<?php

use Illuminate\Database\Seeder;

class DetallePoliticaTransversalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('tbl_parametros_detalles')->insert([

            [
                'i_pk_id'=>7852,
                'vc_parametro_detalle' => 'DESPLAZADOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7853,
                'vc_parametro_detalle' => 'VÍCTIMAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7854,
                'vc_parametro_detalle' => 'GRUPOS ÉTNICOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7855,
                'vc_parametro_detalle' => 'EQUIDAD DE LA MUJER',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7856,
                'vc_parametro_detalle' => 'CONSTRUCCIÓN DE PAZ',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7857,
                'vc_parametro_detalle' => 'INDÍGENAS - CUNDINAMARCA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7858,
                'vc_parametro_detalle' => 'GESTIÓN DE RIESGO DE DESASTRES',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7859,
                'vc_parametro_detalle' => 'CAMBIO CLIMÁTICO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>NULL,
                'i_estado' => 1, 
            ],
            //DESPLAZADOS 7852
            [
                'i_pk_id'=>7860,
                'vc_parametro_detalle' => 'ASISTENCIA - ALIMENTACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7861,
                'vc_parametro_detalle' => 'ASISTENCIA - EDUCACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7862,
                'vc_parametro_detalle' => 'ASISTENCIA - GENERACIÓN DE INGRESOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7863,
                'vc_parametro_detalle' => 'ASISTENCIA - IDENTIFICACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7864,
                'vc_parametro_detalle' => 'ASISTENCIA - REUNIFICACIÓN FAMILIAR - REINTEGRACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7865,
                'vc_parametro_detalle' => 'ASISTENCIA - SALUD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7866,
                'vc_parametro_detalle' => 'ASISTENCIA - SUBSISTENCIA MÍNIMA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7867,
                'vc_parametro_detalle' => 'ASISTENCIA - VIVIENDA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7868,
                'vc_parametro_detalle' => 'ATENCIÓN - TRANSVERSAL/ORIENTACIÓN Y COMUNICACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7869,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - PARTICIPACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7870,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - TRANSVERSAL/COORDINACIÓN NACIÓN-TERRITORIO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7871,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - TRANSVERSAL/COORDINACIÓN NACIONAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7872,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - TRANSVERSAL/SISTEMAS DE INFORMACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7873,
                'vc_parametro_detalle' => 'PREVENCIÓN Y PROTECCIÓN - PROTECCIÓN DE PREDIOS, TIERRAS Y TERRITORIOS ABANDONADOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7874,
                'vc_parametro_detalle' => 'PREVENCIÓN Y PROTECCIÓN - VIDA, SEGURIDAD, LIBERTAD E INTEGRIDAD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7875,
                'vc_parametro_detalle' => 'REPARACIÓN - CRÉDITOS Y PASIVOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7876,
                'vc_parametro_detalle' => 'REPARACIÓN - EMPLEO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7877,
                'vc_parametro_detalle' => 'REPARACIÓN - GARANTÍAS DE NO REPETICIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7878,
                'vc_parametro_detalle' => 'REPARACIÓN - INDEMNIZACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7879,
                'vc_parametro_detalle' => 'REPARACIÓN - REHABILITACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7880,
                'vc_parametro_detalle' => 'REPARACIÓN - REPARACIÓN COLECTIVA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7881,
                'vc_parametro_detalle' => 'REPARACIÓN - RESTITUCIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7882,
                'vc_parametro_detalle' => 'REPARACIÓN - RETORNO Y REUBICACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ],
            [
                'i_pk_id'=>7883,
                'vc_parametro_detalle' => 'REPARACIÓN - SATISFACCIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7852,
                'i_estado' => 1, 
            ], 
            //VÍCTIMAS 7853   
            [
                'i_pk_id'=>7884,
                'vc_parametro_detalle' => 'ASISTENCIA - ALIMENTACIÓN (SOLO VÍCTIMAS DESPLAZAMIENTO)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7885,
                'vc_parametro_detalle' => 'ASISTENCIA - EDUCACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7886,
                'vc_parametro_detalle' => 'ASISTENCIA - GENERACIÓN DE INGRESOS (SOLO VÍCTIMAS DESPLAZAMIENTO)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7887,
                'vc_parametro_detalle' => 'ASISTENCIA - IDENTIFICACIÓN (SOLO VÍCTIMAS DESPLAZAMIENTO)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7888,
                'vc_parametro_detalle' => 'ASISTENCIA - REUNIFICACIÓN FAMILIAR - REINTEGRACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7889,
                'vc_parametro_detalle' => 'ASISTENCIA - SALUD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7890,
                'vc_parametro_detalle' => 'ASISTENCIA - SUBSISTENCIA MÍNIMA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7891,
                'vc_parametro_detalle' => 'ASISTENCIA - VIVIENDA (SOLO VÍCTIMAS DESPLAZAMIENTO)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7892,
                'vc_parametro_detalle' => 'ATENCIÓN - TRANSVERSAL/ORIENTACIÓN Y COMUNICACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7893,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - PARTICIPACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7894,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - TRANSVERSAL/COORDINACIÓN NACIÓN-TERRITORIO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7895,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - TRANSVERSAL/COORDINACIÓN NACIONAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7896,
                'vc_parametro_detalle' => 'EJES TRANSVERSALES - TRANSVERSAL/SISTEMAS DE INFORMACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7897,
                'vc_parametro_detalle' => 'PREVENCIÓN Y PROTECCIÓN - PROTECCIÓN DE PREDIOS, TIERRAS Y TERRITORIOS ABANDONADOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7898,
                'vc_parametro_detalle' => 'PREVENCIÓN Y PROTECCIÓN - VIDA, SEGURIDAD, LIBERTAD E INTEGRIDAD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7899,
                'vc_parametro_detalle' => 'REPARACIÓN - CRÉDITOS Y PASIVOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7900,
                'vc_parametro_detalle' => 'REPARACIÓN - EMPLEO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7901,
                'vc_parametro_detalle' => 'REPARACIÓN - GARANTÍAS DE NO REPETICIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7902,
                'vc_parametro_detalle' => 'REPARACIÓN - INDEMNIZACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7903,
                'vc_parametro_detalle' => 'REPARACIÓN - REHABILITACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7904,
                'vc_parametro_detalle' => 'REPARACIÓN - REPARACIÓN COLECTIVA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7905,
                'vc_parametro_detalle' => 'REPARACIÓN - RESTITUCIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7906,
                'vc_parametro_detalle' => 'REPARACIÓN - RETORNO Y REUBICACIÓN (SOLO VÍCTIMAS DESPLAZAMIENTO)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7907,
                'vc_parametro_detalle' => 'REPARACIÓN - SATISFACCIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7853,
                'i_estado' => 1, 
            ], 
            //GRUPOS ÉTNICOS 7854
            [
                'i_pk_id'=>7908,
                'vc_parametro_detalle' => 'POBLACIÓN AFROCOLOMBIANA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7854,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7909,
                'vc_parametro_detalle' => 'POBLACIÓN RAIZAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7854,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7910,
                'vc_parametro_detalle' => 'PUEBLO RROM',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7854,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7911,
                'vc_parametro_detalle' => 'PUEBLOS INDÍGENAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7854,
                'i_estado' => 1, 
            ], 
            //EQUIDAD DE LA MUJER 7855
            [
                'i_pk_id'=>7912,
                'vc_parametro_detalle' => 'AUTONOMÍA ECONÓMICA Y ACCESO A ACTIVOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7913,
                'vc_parametro_detalle' => 'AUTONOMÍA ECONÓMICA Y ACCESO A ACTIVOS - DESARROLLO INSTITUCIONAL Y TRANSFORMACIÓN CULTURAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7914,
                'vc_parametro_detalle' => 'EDUCACIÓN Y ACCESO A NUEVAS TECNOLOGÍAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7915,
                'vc_parametro_detalle' => 'EDUCACIÓN Y ACCESO A NUEVAS TECNOLOGÍAS - DESARROLLO INSTITUCIONAL Y TRANSFORMACIÓN CULTURAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7916,
                'vc_parametro_detalle' => 'MUJER LIBRE DE VIOLENCIAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7917,
                'vc_parametro_detalle' => 'MUJER LIBRE DE VIOLENCIAS - DESARROLLO INSTITUCIONAL Y TRANSFORMACIÓN CULTURAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7918,
                'vc_parametro_detalle' => 'PARTICIPACIÓN EN LOS ESCENARIOS DE PODER Y TOMA DE DECISIONES',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7919,
                'vc_parametro_detalle' => 'PARTICIPACIÓN EN LOS ESCENARIOS DE PODER Y TOMA DE DECISIONES - DESARROLLO INSTITUCIONAL Y TRANSFORMACIÓN CULTURAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7920,
                'vc_parametro_detalle' => 'SALUD Y DERECHOS SEXUALES Y REPRODUCTIVOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7921,
                'vc_parametro_detalle' => 'SALUD Y DERECHOS SEXUALES Y REPRODUCTIVOS - DESARROLLO INSTITUCIONAL Y TRANSFORMACIÓN CULTURAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7855,
                'i_estado' => 1, 
            ], 
            //CONSTRUCCIÓN DE PAZ 7856
            [
                'i_pk_id'=>7922,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.1. ORDENAMIENTO SOCIAL DE LA PROPIEDAD RURAL Y USO DEL SUELO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7923,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.2. INFRAESTRUCTURA Y ADECUACIÓN DE TIERRAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7924,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.3. DESARROLLO SOCIAL: SALUD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7925,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.4. DESARROLLO SOCIAL: EDUCACIÓN RURAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7926,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.5. DESARROLLO SOCIAL: VIVIENDA Y AGUA POTABLE',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7927,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.6. PRODUCCIÓN AGROPECUARIA Y ECONOMÍA SOLIDARIA Y COOPERATIVA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7928,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.7. GARANTÍA PROGRESIVA DEL DERECHO A LA ALIMENTACIÓN.',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7929,
                'vc_parametro_detalle' => '1. REFORMA RURAL INTEGRAL - 1.8. PLANES DE ACCIÓN PARA LA TRANSFORMACIÓN REGIONAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7930,
                'vc_parametro_detalle' => '1.99. INICIATIVAS PATR (SIN INDICADORES PMI)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7931,
                'vc_parametro_detalle' => '2. PARTICIPACIÓN POLÍTICA - 2.1 DERECHOS Y GARANTÍAS PLENAS PARA EL EJERCICIO DE LA OPOSICIÓN POLÍTICA EN GENERAL, Y EN PARTICULAR PARA LOS NUEVOS MOVIMIENTOS QUE SURJAN LUEGO DE LA FIRMA DEL ACUERDO FINAL.',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7932,
                'vc_parametro_detalle' => '2. PARTICIPACIÓN POLÍTICA - 2.2 MECANISMOS DEMOCRÁTICOS DE PARTICIPACIÓN CIUDADANA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7933,
                'vc_parametro_detalle' => '2. PARTICIPACIÓN POLÍTICA - 2.3 PROMOCIÓN DE UNA MAYOR PARTICIPACIÓN EN LA POLÍTICA NACIONAL, REGIONAL Y LOCAL, EN IGUALDAD DE CONDICIONES Y CON GARANTÍAS DE SEGURIDAD.',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7934,
                'vc_parametro_detalle' => '3. FIN DEL CONFLICTO - 3.1 CESE AL FUEGO Y DE HOSTILIDADES BILATERAL Y DEFINITIVO Y DEJACIÓN DE ARMAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7935,
                'vc_parametro_detalle' => '3. FIN DEL CONFLICTO - 3.2 REINCORPORACIÓN DE LAS FARC EP A LA VIDA CIVIL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7936,
                'vc_parametro_detalle' => '3. FIN DEL CONFLICTO - 3.3 GARANTÍAS DE SEGURIDAD Y LUCHA CONTRA LAS ORGANIZACIONES Y CONDUCTAS CRIMINALES',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7937,
                'vc_parametro_detalle' => '4. SOLUCIÓN AL PROBLEMA DE LAS DROGAS - 4.1. PROGRAMA NACIONAL INTEGRAL DE SUSTITUCIÓN DE CULTIVOS DE USO ILÍCITO -PNIS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7938,
                'vc_parametro_detalle' => '4. SOLUCIÓN AL PROBLEMA DE LAS DROGAS - 4.2. PREVENCIÓN DEL CONSUMO Y SALUD PÚBLICA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7939,
                'vc_parametro_detalle' => '4. SOLUCIÓN AL PROBLEMA DE LAS DROGAS - 4.3. SOLUCIÓN AL FENÓMENO DE PRODUCCIÓN Y COMERCIALIZACIÓN DE NARCÓTICOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7940,
                'vc_parametro_detalle' => '5. VÍCTIMAS DEL CONFLICTO - 5.1 JUSTICIA Y VERDAD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7941,
                'vc_parametro_detalle' => '5. VÍCTIMAS DEL CONFLICTO - 5.4 REPARACIÓN INTEGRAL PARA LA CONSTRUCCIÓN DE PAZ',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7942,
                'vc_parametro_detalle' => '5. VÍCTIMAS DEL CONFLICTO - 5.6 DERECHOS HUMANOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7943,
                'vc_parametro_detalle' => '6. IMPLEMENTACIÓN, VERIFICACIÓN Y REFRENDACIÓN - 6.1 MECANISMOS DE IMPLEMENTACIÓN Y VERIFICACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7944,
                'vc_parametro_detalle' => '6. IMPLEMENTACIÓN, VERIFICACIÓN Y REFRENDACIÓN - 6.2 CAPÍTULO ÉTNICO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7945,
                'vc_parametro_detalle' => '6. IMPLEMENTACIÓN, VERIFICACIÓN Y REFRENDACIÓN - 6.3. COMPONENTE INTERNACIONAL DE VERIFICACIÓN DE LA COMISIÓN DE SEGUIMIENTO, IMPULSO Y VERIFICACIÓN A LA IMPLEMENTACIÓN DEL ACUERDO FINAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7946,
                'vc_parametro_detalle' => '6. IMPLEMENTACIÓN, VERIFICACIÓN Y REFRENDACIÓN - 6.4. COMPONENTE DE ACOMPAÑAMIENTO INTERNACIONAL',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7947,
                'vc_parametro_detalle' => '6. IMPLEMENTACIÓN, VERIFICACIÓN Y REFRENDACIÓN - 6.5. HERRAMIENTAS DE DIFUSIÓN Y COMUNICACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7856,
                'i_estado' => 1, 
            ], 
            //INDIGENAS - CUNDINAMARCA 7857
            [
                'i_pk_id'=>7949,
                'vc_parametro_detalle' => 'CHÍA FONQUETÁ Y CERCA DE PIEDRA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7857,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7950,
                'vc_parametro_detalle' => 'COTA MUISCA DE COTA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7857,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7951,
                'vc_parametro_detalle' => 'POBLACIÓN NO RESGUARDADA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7857,
                'i_estado' => 1, 
            ], 
            // GESTIÓN DE RIESGO DE DESASTRES 7858            
            [
                'i_pk_id'=>7952,
                'vc_parametro_detalle' => 'CONOCIMIENTO DEL RIESGO - CARACTERIZACIÓN DE ESCENARIOS, ANÁLISIS Y EVALUACIÓN DEL RIESGO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7953,
                'vc_parametro_detalle' => 'CONOCIMIENTO DEL RIESGO - COMUNICACIÓN Y APROPIACIÓN SOCIAL DEL RIESGO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7954,
                'vc_parametro_detalle' => 'CONOCIMIENTO DEL RIESGO - MONITOREO Y SEGUIMIENTO DEL RIESGO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7955,
                'vc_parametro_detalle' => 'GOBERNANZA PARA LA GESTIÓN DE RIESGO DE DESASTRES - FORTALECIMIENTO DE LA POLÍTICA Y/O PLAN NACIONAL DE GESTIÓN DEL RIESGO DE DESASTRES',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7956,
                'vc_parametro_detalle' => 'GOBERNANZA PARA LA GESTIÓN DE RIESGO DE DESASTRES - FORTALECIMIENTO DE LAS  ENTIDADES DEL SNGRD',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7957,
                'vc_parametro_detalle' => 'MANEJO DE DESASTRES - PREPARACIÓN PARA LA RECUPERACIÓN (REHABILITACIÓN Y RECONSTRUCCIÓN)',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7958,
                'vc_parametro_detalle' => 'MANEJO DE DESASTRES - PREPARACIÓN Y/O EJECUCIÓN PARA LA RESPUESTA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7959,
                'vc_parametro_detalle' => 'REDUCCIÓN DEL RIESGO - INTERVENCIONES CORRECTIVAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7960,
                'vc_parametro_detalle' => 'REDUCCIÓN DEL RIESGO - INTERVENCIONES PROSPECTIVAS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7961,
                'vc_parametro_detalle' => 'REDUCCIÓN DEL RIESGO - PROTECCIÓN FINANCIERA',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7858,
                'i_estado' => 1, 
            ], 
            // gestion del cambio 7859
            [
                'i_pk_id'=>7962,
                'vc_parametro_detalle' => 'ADAPTACIÓN. EDUCACIÓN, FORMACIÓN Y SENSIBILIZACIÓN A PÚBLICOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7963,
                'vc_parametro_detalle' => 'ADAPTACIÓN. FINANCIACIÓN E INSTRUMENTOS ECONÓMICOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7964,
                'vc_parametro_detalle' => 'ADAPTACIÓN. IMPLEMENTACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7965,
                'vc_parametro_detalle' => 'ADAPTACIÓN. INFORMACIÓN, CIENCIA, TECNOLOGÍA E INNOVACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7966,
                'vc_parametro_detalle' => 'ADAPTACIÓN. PLANIFICACIÓN DE LA GESTIÓN DEL CAMBIO CLIMÁTICO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7967,
                'vc_parametro_detalle' => 'ADAPTACIÓN. SEGUIMIENTO Y EVALUACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7968,
                'vc_parametro_detalle' => 'MITIGACIÓN. EDUCACIÓN, FORMACIÓN Y SENSIBILIZACIÓN A PÚBLICOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7969,
                'vc_parametro_detalle' => 'MITIGACIÓN. FINANCIACIÓN E INSTRUMENTOS ECONÓMICOS',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7970,
                'vc_parametro_detalle' => 'MITIGACIÓN. INFORMACIÓN, CIENCIA, TECNOLOGÍA E INNOVACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7971,
                'vc_parametro_detalle' => 'MITIGACIÓN. PLANIFICACIÓN DE LA GESTIÓN DEL CAMBIO CLIMÁTICO',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7972,
                'vc_parametro_detalle' => 'MITIGACIÓN. SEGUIMIENTO Y EVALUACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 
            [
                'i_pk_id'=>7973,
                'vc_parametro_detalle' => 'MITIGACIÓN.IMPLEMENTACIÓN',
                'i_fk_id_parametro' => 63,
                'vc_codigo_interno'=>'',
                'i_fk_id_padre'=>7859,
                'i_estado' => 1, 
            ], 

        ]);        
    }
}
